/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ClienteController;
import Controllers.EmpleadoController;
import Controllers.ProductoController;
import Controllers.ProveedorController;
import Models.DetalleVenta;
import Models.Empleados.Empleado;
import Models.Venta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class TablaVentaDetalleView extends javax.swing.JFrame {

    /**
     * Creates new form TablaVentaDetalleView
     */
    ProductoController pc;
    EmpleadoController ec;
    ClienteController cc;
    ProveedorController pvC;
    Empleado empleado;
    public TablaVentaDetalleView(ProductoController pc, EmpleadoController ec, ClienteController cc, ProveedorController pvC, Empleado empleado, int idVenta) {
        initComponents();
        setLocationRelativeTo(this);
        this.pc = pc;
        this.pvC = pvC;
        this.ec = ec;
        this.cc = cc;
        this.empleado = empleado;
        llenarTabla(idVenta);
        mostrarInfoVenta(idVenta);
    }
    
    private void llenarTabla(int idVenta) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new Object[]{"ID Detalle", "Cod Producto", "Nombre", "Cantidad", "Precio"});

        for (DetalleVenta detalle : cc.getDetallesVenta(idVenta)) {
            tableModel.addRow(new Object[]{
                detalle.getIdDetalle(),
                detalle.getProducto().getCodigoProducto(),
                detalle.getProducto().getNombreProducto(),
                detalle.getCantidad(),
            detalle.getPrecio()});
        }

        tablaDetalleVenta.setModel(tableModel);
    }
    private void mostrarInfoVenta(int idVenta) {
        Venta venta = cc.getVentaPorId(idVenta);
        clienteL.setText(venta.getCliente().getIdCliente() + ". " + venta.getCliente().getNombreCompleto());
        cajeroL.setText(venta.getCajero().getIdEmpleado() + ". " + venta.getCajero().getNombreCompleto());
        fechaL.setText(venta.getFecha());
        totalL.setText(venta.getTotal() + "");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleVenta = new javax.swing.JTable();
        regresarBtn = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        cajeroLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        clienteL = new javax.swing.JLabel();
        cajeroL = new javax.swing.JLabel();
        fechaL = new javax.swing.JLabel();
        totalL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Detalles de la venta");

        tablaDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalleVenta);

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        totalLabel.setText("Total:");

        clienteLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clienteLabel.setText("Cliente:");

        cajeroLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cajeroLabel.setText("Cajero:");

        fechaLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fechaLabel.setText("Fecha:");

        clienteL.setText("jLabel2");

        cajeroL.setText("jLabel3");

        fechaL.setText("jLabel2");

        totalL.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(18, 18, 18)
                                .addComponent(totalL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regresarBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteL)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cajeroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajeroL)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaL)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(cajeroLabel)
                    .addComponent(fechaLabel)
                    .addComponent(clienteL)
                    .addComponent(cajeroL)
                    .addComponent(fechaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarBtn)
                    .addComponent(totalLabel)
                    .addComponent(totalL))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        new GestionClientesView(pc, ec, cc, pvC, empleado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cajeroL;
    private javax.swing.JLabel cajeroLabel;
    private javax.swing.JLabel clienteL;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel fechaL;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JTable tablaDetalleVenta;
    private javax.swing.JLabel totalL;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
