/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ProductoController;
import Exceptions.StockInsuficienteException;
import Models.Empleados.Reponedor;
import Models.Productos.Producto;
import Models.Productos.ProductoNoPerecedero;
import Models.Productos.ProductoPerecedero;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ViewReponedor extends javax.swing.JFrame {

    /**
     * Creates new form ViewReponedor
     */
    ProductoController pc;
    int codProductoSeleccionado = -1;
    int stockSeleccionado;
    public ViewReponedor(Reponedor reponedor) {
        initComponents();
        setLocationRelativeTo(this);
        pc = new ProductoController();
        
        usuarioLabel.setText(reponedor.getNombreCompleto());
        alistarTabla();
        configurarSeleccionTablaProductos();
    }
    private void alistarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.setColumnIdentifiers(new Object[]{"Codigo", "Nombre", "Precio", "Stock", "Tipo","Proveedor", "Caducidad", "DuracionAlmacen"});
        
        for (int i = 0; i < pc.getProductos(3, stockBajoCheckbox.isSelected()).size(); i++) {
            Producto pro = pc.getProductos(3, stockBajoCheckbox.isSelected()).get(i);
            modelo.addRow(new Object[]{
                pro.getCodigoProducto(),
                pro.getNombreProducto(),
                pro.getPrecio(),
                pro.getStock(),
                pro.getClass().getSimpleName().equals("ProductoPerecedero")? "Perecedero":"NoPerecedero",
                pro.getIdProveedor(),
                pro instanceof ProductoPerecedero? ((ProductoPerecedero)pro).getFechaCaducidad() : "",
                pro instanceof ProductoNoPerecedero? ((ProductoNoPerecedero)pro).getDuracionAlmacen() : ""
            });
        }
        tablaProductos.setModel(modelo);
    }
    private void configurarSeleccionTablaProductos() {
        tablaProductos.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                int filaSeleccionada = tablaProductos.getSelectedRow();

                if (filaSeleccionada != -1) {
                    Object codProd = tablaProductos.getValueAt(filaSeleccionada, 0);
                    Object stockProd = tablaProductos.getValueAt(filaSeleccionada, 3);
                    this.codProductoSeleccionado = Integer.parseInt(codProd.toString());
                    this.stockSeleccionado = Integer.parseInt(stockProd.toString());
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nuevoStockField = new javax.swing.JTextField();
        reponerStockBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        stockBajoCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("REPONER STOCK DE PRODUCTOS");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jLabel3.setText("Nuevo stock");

        reponerStockBtn.setText("Reponer Stock");
        reponerStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponerStockBtnActionPerformed(evt);
            }
        });

        regresarBtn.setText("Cerrar Sesión");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Usuario:");

        usuarioLabel.setText("jLabel5");

        stockBajoCheckbox.setText("Stocks Debajo de 15");
        stockBajoCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBajoCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(regresarBtn)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(stockBajoCheckbox))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(reponerStockBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevoStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(usuarioLabel)
                            .addComponent(regresarBtn))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(stockBajoCheckbox)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addComponent(reponerStockBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        new PrincipalView(null, null, null, null).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void stockBajoCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBajoCheckboxActionPerformed
        alistarTabla();
    }//GEN-LAST:event_stockBajoCheckboxActionPerformed

    private void reponerStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponerStockBtnActionPerformed
        try {
            if (codProductoSeleccionado != -1) {
                int nuevoStock = Integer.parseInt(nuevoStockField.getText());
                pc.editarStock(codProductoSeleccionado, nuevoStock, stockSeleccionado);
                
                alistarTabla();
                this.codProductoSeleccionado = -1;
                JOptionPane.showMessageDialog(this, "¡STOCK DE PRODUCTO EDITADO EXITOSAMENTE!");
            } else{
                JOptionPane.showMessageDialog(this, "Por favor selecciona un producto de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El stock debe ser un número válido", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (StockInsuficienteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_reponerStockBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nuevoStockField;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JButton reponerStockBtn;
    private javax.swing.JCheckBox stockBajoCheckbox;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
